[unix_http_server]
file=/var/run/supervisor.sock
chmod=0700

[rpcinterface:supervisor]
supervisor.rpcinterface_factory = supervisor.rpcinterface:make_main_rpcinterface

[supervisorctl]
serverurl=unix:///var/run/supervisor.sock

[supervisord]
nodaemon=true
user=root
logfile=/var/log/supervisor/supervisord.log
pidfile=/var/run/supervisord.pid

[program:php-fpm]
command=/usr/local/sbin/php-fpm -F  # Alpine: -F keeps process in foreground
autostart=true
autorestart=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0

[program:nginx]
command=/usr/sbin/nginx -g "daemon off;" # Absolute path for Ubuntu nginx
autostart=true
autorestart=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0

# [program:reverb]
# command=/usr/local/bin/php /var/www/artisan reverb:start --host=0.0.0.0 --port=2002
# autostart=true
# autorestart=true
# user=www-data
# stdout_logfile=/dev/stdout
# stdout_logfile_maxbytes=0
# stderr_logfile=/dev/stderr
# stderr_logfile_maxbytes=0

# [program:notify]
# process_name=%(program_name)s_%(process_num)02d
# command=/usr/local/bin/php /var/www/artisan queue:work rabbitmq --queue=notify
# autostart=true
# autorestart=true
# user=www-data
# numprocs=1
# redirect_stderr=true
# stdout_logfile=/var/www/storage/logs/worker.log
# stopwaitsecs=60
